baseURL = "https://denken.slm.space/"
languageCode = "en-us"
title = "Sebastian Mellen's Thinking/Denken"
theme = "microBlog"

[params]
    author = "Sebastian Mellen"

[permalinks]
  posts = "/:year/:month/:title/"
